-- ════════════════════════════════════════════════════════════════════════
-- ZaDeteto 2.0 — 100 mockup partners for visual / UX testing
--
-- ⚠️  ALL ROWS HAVE is_sample = true. Real partner data must NEVER have
--     is_sample = true. See supabase/sample-data-tracking.md for the full
--     safety story.
--
-- PREREQUISITES (apply these migrations first):
--   - 0001_initial_schema.sql
--   - 0002_fix_anon_insert_policies.sql
--   - 0003_listing_enrichment.sql        (adds working_hours, gallery_urls)
--   - 0004_is_sample_flag.sql            (adds is_sample column)
--
-- INSERT THIS FILE: paste into Supabase SQL Editor → Run.
-- ~5 seconds. Adds 100 rows to public.businesses.
--
-- VERIFY:
--   SELECT count(*), is_sample FROM public.businesses GROUP BY is_sample;
--
-- CLEANUP (deletes ALL mockup data including these 100 + the 6 from
-- sample-businesses.sql, NEVER touches real partner rows):
--   DELETE FROM public.businesses WHERE is_sample = true;
--
-- DISTRIBUTION:
--   100 rows total
--   Tiers:        10 Доверен, 25 Проверен, 40 Стандартен, 25 Безплатен
--   Cities:       40% София, 15% Пловдив, 12% Варна, 10% Бургас,
--                  5% Стара Загора, 5% Русе, 5% Велико Търново,
--                  5% Онлайн, 3% other
--   Categories:   round-robin across all 8 (12-13 per category)
--   SOP flag:     ~14% (every 7th row)
--   With description: paid tiers only (50%)
--   With working hours: every 4th paid tier (~12 rows)
--   With phone:   80% (every 5th has none)
--   Lat/lng:      all rows except Онлайн (~95%)
--
-- Safe to re-run: ON CONFLICT (legacy_id) DO UPDATE so existing mock-NNN
-- rows get refreshed instead of duplicated.
-- ════════════════════════════════════════════════════════════════════════

INSERT INTO public.businesses (
  legacy_id, name, tier, city, address, lat, lng,
  description, services, categories, age_groups,
  logo, audit_score, sop, phone, email, website,
  facebook, instagram, cta_label_1, cta_url_1, cta_label_2, cta_url_2,
  working_hours, gallery_urls, published, is_sample
) VALUES
(
  'mock-001',
  'Д-р Иванова Психология',
  'Доверен',
  'София',
  'ул. 14, София',
  42.7287, 23.3589,
  'Д-р Иванова Психология предлага професионални услуги в категория Специалисти. Опит, качество, индивидуален подход. Работим с деца от различни възрастови групи. Сертифицирани специалисти.',
  ARRAY['Терапия', 'Консултация', 'Диагностика', 'Групова терапия'],
  ARRAY['Специалисти'],
  ARRAY['3-5', '13-19'],
  'https://placehold.co/200x200/7c4dff/white?text=M001',
  117, false,
  '+359 88 017 0041',
  'biz001@example.bg',
  'https://example1.bg',
  'https://facebook.com/biz1', null,
  'Запиши се', 'https://example1.bg/signup',
  'Виж повече', 'https://example1.bg/info',
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-002',
  'Little Engineers',
  'Доверен',
  'София',
  'ул. 27, София',
  42.7597, 23.3959,
  'Little Engineers предлага професионални услуги в категория Учене и умения. Опит, качество, индивидуален подход. Работим с деца от различни възрастови групи. Сертифицирани специалисти.',
  ARRAY['Курсове', 'Уроци', 'Лятна школа', 'Олимпиади'],
  ARRAY['Учене и умения'],
  ARRAY['6-12', 'Тийнейджъри', '3-5'],
  'https://placehold.co/200x200/7c4dff/white?text=M002',
  134, false,
  '+359 88 034 0082',
  'biz002@example.bg',
  'https://example2.bg',
  'https://facebook.com/biz2', 'https://instagram.com/biz2',
  'Запиши се', 'https://example2.bg/signup',
  'Виж повече', 'https://example2.bg/info',
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-003',
  'Детски център Слънчо',
  'Доверен',
  'София',
  'ул. 40, София',
  42.7907, 23.3329,
  'Детски център Слънчо предлага професионални услуги в категория Игри и забавления. Опит, качество, индивидуален подход. Работим с деца от различни възрастови групи. Сертифицирани специалисти.',
  ARRAY['Парти', 'Аниматори', 'Игри', 'Творчество'],
  ARRAY['Игри и забавления'],
  ARRAY['13-19'],
  'https://placehold.co/200x200/7c4dff/white?text=M003',
  151, false,
  '+359 88 051 0123',
  'biz003@example.bg',
  'https://example3.bg',
  'https://facebook.com/biz3', null,
  'Запиши се', 'https://example3.bg/signup',
  'Виж повече', 'https://example3.bg/info',
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-004',
  'Театър Пинокио',
  'Доверен',
  'София',
  'ул. 53, София',
  42.7217, 23.3699,
  'Театър Пинокио предлага професионални услуги в категория Култура. Опит, качество, индивидуален подход. Работим с деца от различни възрастови групи. Сертифицирани специалисти.',
  ARRAY['Представления', 'Уъркшопи', 'Работилници', 'Лагери'],
  ARRAY['Култура'],
  ARRAY['Тийнейджъри', '3-5'],
  'https://placehold.co/200x200/7c4dff/white?text=M004',
  168, false,
  '+359 88 068 0164',
  'biz004@example.bg',
  'https://example4.bg',
  'https://facebook.com/biz4', 'https://instagram.com/biz4',
  'Запиши се', 'https://example4.bg/signup',
  'Виж повече', 'https://example4.bg/info',
  '{"mon":"9:00-18:00","tue":"9:00-18:00","wed":"9:00-18:00","thu":"9:00-18:00","fri":"9:00-18:00","sat":"10:00-15:00","sun":"closed"}'::jsonb,
  ARRAY[]::text[],
  true, true
),
(
  'mock-005',
  'Футболна школа Виктория',
  'Доверен',
  'София',
  'ул. 66, София',
  42.7527, 23.4069,
  'Футболна школа Виктория предлага професионални услуги в категория Спорт и движение. Опит, качество, индивидуален подход. Работим с деца от различни възрастови групи. Сертифицирани специалисти.',
  ARRAY['Тренировки', 'Турнири', 'Лагер', 'Лични уроци'],
  ARRAY['Спорт и движение'],
  ARRAY['0-3', '6-12', 'Тийнейджъри'],
  'https://placehold.co/200x200/7c4dff/white?text=M005',
  185, false,
  null,
  'biz005@example.bg',
  'https://example5.bg',
  'https://facebook.com/biz5', null,
  'Запиши се', 'https://example5.bg/signup',
  'Виж повече', 'https://example5.bg/info',
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-006',
  'Парти зала Феерия',
  'Доверен',
  'София',
  'ул. 79, София',
  42.7837, 23.3439,
  'Парти зала Феерия предлага професионални услуги в категория Тържества и събития. Опит, качество, индивидуален подход. Работим с деца от различни възрастови групи. Сертифицирани специалисти.',
  ARRAY['Аниматори', 'Декорация', 'Кетъринг', 'Фото'],
  ARRAY['Тържества и събития'],
  ARRAY['3-5'],
  'https://placehold.co/200x200/7c4dff/white?text=M006',
  102, false,
  '+359 88 102 0246',
  'biz006@example.bg',
  'https://example6.bg',
  'https://facebook.com/biz6', 'https://instagram.com/biz6',
  'Запиши се', 'https://example6.bg/signup',
  'Виж повече', 'https://example6.bg/info',
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-007',
  'Бебешки магазин Бамби',
  'Доверен',
  'София',
  'ул. 92, София',
  42.7147, 23.3809,
  'Бебешки магазин Бамби предлага професионални услуги в категория Стоки. Опит, качество, индивидуален подход. Работим с деца от различни възрастови групи. Сертифицирани специалисти.',
  ARRAY['Дрехи', 'Играчки', 'Аксесоари', 'Книги'],
  ARRAY['Стоки'],
  ARRAY['6-12', 'Тийнейджъри'],
  'https://placehold.co/200x200/7c4dff/white?text=M007',
  119, true,
  '+359 88 119 0287',
  'biz007@example.bg',
  'https://example7.bg',
  'https://facebook.com/biz7', null,
  'Запиши се', 'https://example7.bg/signup',
  'Виж повече', 'https://example7.bg/info',
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-008',
  'Детегледач СЪН',
  'Доверен',
  'София',
  'ул. 105, София',
  42.7457, 23.4179,
  'Детегледач СЪН предлага професионални услуги в категория Домашна грижа и помощ. Опит, качество, индивидуален подход. Работим с деца от различни възрастови групи. Сертифицирани специалисти.',
  ARRAY['Домашни услуги', 'Бавачка', 'Помощ', 'Грижа'],
  ARRAY['Домашна грижа и помощ'],
  ARRAY['13-19', '0-3', '6-12'],
  'https://placehold.co/200x200/7c4dff/white?text=M008',
  136, false,
  '+359 88 136 0328',
  'biz008@example.bg',
  'https://example8.bg',
  'https://facebook.com/biz8', 'https://instagram.com/biz8',
  'Запиши се', 'https://example8.bg/signup',
  'Виж повече', 'https://example8.bg/info',
  '{"mon":"9:00-18:00","tue":"9:00-18:00","wed":"9:00-18:00","thu":"9:00-18:00","fri":"9:00-18:00","sat":"10:00-15:00","sun":"closed"}'::jsonb,
  ARRAY[]::text[],
  true, true
),
(
  'mock-009',
  'Логопед Студио Реч',
  'Доверен',
  'Пловдив',
  'ул. 118, Пловдив',
  42.2144, 24.7783,
  'Логопед Студио Реч предлага професионални услуги в категория Специалисти. Опит, качество, индивидуален подход. Работим с деца от различни възрастови групи. Сертифицирани специалисти.',
  ARRAY['Терапия', 'Консултация', 'Диагностика', 'Групова терапия'],
  ARRAY['Специалисти'],
  ARRAY['Тийнейджъри'],
  'https://placehold.co/200x200/7c4dff/white?text=M009',
  153, false,
  '+359 88 153 0369',
  'biz009@example.bg',
  'https://example9.bg',
  'https://facebook.com/biz9', null,
  'Запиши се', 'https://example9.bg/signup',
  'Виж повече', 'https://example9.bg/info',
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-010',
  'Robo Academy',
  'Доверен',
  'Пловдив',
  'ул. 131, Пловдив',
  42.1454, 24.8153,
  'Robo Academy предлага професионални услуги в категория Учене и умения. Опит, качество, индивидуален подход. Работим с деца от различни възрастови групи. Сертифицирани специалисти.',
  ARRAY['Курсове', 'Уроци', 'Лятна школа', 'Олимпиади'],
  ARRAY['Учене и умения'],
  ARRAY['0-3', '6-12'],
  'https://placehold.co/200x200/7c4dff/white?text=M010',
  170, false,
  null,
  'biz010@example.bg',
  'https://example10.bg',
  'https://facebook.com/biz10', 'https://instagram.com/biz10',
  'Запиши се', 'https://example10.bg/signup',
  'Виж повече', 'https://example10.bg/info',
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-011',
  'Игротека Дъга',
  'Проверен',
  'Пловдив',
  'ул. 144, Пловдив',
  42.1764, 24.7523,
  'Игротека Дъга предлага професионални услуги в категория Игри и забавления. Опит, качество, индивидуален подход. Работим с деца от различни възрастови групи. Сертифицирани специалисти.',
  ARRAY['Парти', 'Аниматори', 'Игри', 'Творчество'],
  ARRAY['Игри и забавления'],
  ARRAY['3-5', '13-19', '0-3'],
  'https://placehold.co/200x200/2e994d/white?text=M011',
  133, false,
  '+359 88 187 0451',
  'biz011@example.bg',
  'https://example11.bg',
  'https://facebook.com/biz11', null,
  'Резервирай', 'https://example11.bg/book',
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-012',
  'Куклен театър Капчица',
  'Проверен',
  'Варна',
  'ул. 157, Варна',
  43.2861, 27.9587,
  'Куклен театър Капчица предлага професионални услуги в категория Култура. Опит, качество, индивидуален подход. Работим с деца от различни възрастови групи. Сертифицирани специалисти.',
  ARRAY['Представления', 'Уъркшопи', 'Работилници', 'Лагери'],
  ARRAY['Култура'],
  ARRAY['6-12'],
  'https://placehold.co/200x200/2e994d/white?text=M012',
  146, false,
  '+359 88 204 0492',
  'biz012@example.bg',
  'https://example12.bg',
  'https://facebook.com/biz12', 'https://instagram.com/biz12',
  'Резервирай', 'https://example12.bg/book',
  null, null,
  '{"mon":"9:00-18:00","tue":"9:00-18:00","wed":"9:00-18:00","thu":"9:00-18:00","fri":"9:00-18:00","sat":"10:00-15:00","sun":"closed"}'::jsonb,
  ARRAY[]::text[],
  true, true
),
(
  'mock-013',
  'Плувен клуб Делфин',
  'Проверен',
  'Варна',
  'ул. 170, Варна',
  43.2171, 27.9957,
  'Плувен клуб Делфин предлага професионални услуги в категория Спорт и движение. Опит, качество, индивидуален подход. Работим с деца от различни възрастови групи. Сертифицирани специалисти.',
  ARRAY['Тренировки', 'Турнири', 'Лагер', 'Лични уроци'],
  ARRAY['Спорт и движение'],
  ARRAY['13-19', '0-3'],
  'https://placehold.co/200x200/2e994d/white?text=M013',
  79, false,
  '+359 88 221 0533',
  'biz013@example.bg',
  'https://example13.bg',
  'https://facebook.com/biz13', null,
  'Резервирай', 'https://example13.bg/book',
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-014',
  'Аниматори Усмивка',
  'Проверен',
  'Варна',
  'ул. 183, Варна',
  43.2481, 27.9327,
  'Аниматори Усмивка предлага професионални услуги в категория Тържества и събития. Опит, качество, индивидуален подход. Работим с деца от различни възрастови групи. Сертифицирани специалисти.',
  ARRAY['Аниматори', 'Декорация', 'Кетъринг', 'Фото'],
  ARRAY['Тържества и събития'],
  ARRAY['Тийнейджъри', '3-5', '13-19'],
  'https://placehold.co/200x200/2e994d/white?text=M014',
  92, true,
  '+359 88 238 0574',
  'biz014@example.bg',
  'https://example14.bg',
  'https://facebook.com/biz14', 'https://instagram.com/biz14',
  'Резервирай', 'https://example14.bg/book',
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-015',
  'Дрехи KidStyle',
  'Проверен',
  'Бургас',
  'ул. 196, Бургас',
  42.5698, 27.5176,
  'Дрехи KidStyle предлага професионални услуги в категория Стоки. Опит, качество, индивидуален подход. Работим с деца от различни възрастови групи. Сертифицирани специалисти.',
  ARRAY['Дрехи', 'Играчки', 'Аксесоари', 'Книги'],
  ARRAY['Стоки'],
  ARRAY['0-3'],
  'https://placehold.co/200x200/2e994d/white?text=M015',
  105, false,
  null,
  'biz015@example.bg',
  'https://example15.bg',
  'https://facebook.com/biz15', null,
  'Резервирай', 'https://example15.bg/book',
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-016',
  'Бавачка PRO',
  'Проверен',
  'Бургас',
  'ул. 9, Бургас',
  42.6008, 27.5546,
  'Бавачка PRO предлага професионални услуги в категория Домашна грижа и помощ. Опит, качество, индивидуален подход. Работим с деца от различни възрастови групи. Сертифицирани специалисти.',
  ARRAY['Домашни услуги', 'Бавачка', 'Помощ', 'Грижа'],
  ARRAY['Домашна грижа и помощ'],
  ARRAY['3-5', '13-19'],
  'https://placehold.co/200x200/2e994d/white?text=M016',
  118, false,
  '+359 88 272 0656',
  'biz016@example.bg',
  'https://example16.bg',
  'https://facebook.com/biz16', 'https://instagram.com/biz16',
  'Резервирай', 'https://example16.bg/book',
  null, null,
  '{"mon":"9:00-18:00","tue":"9:00-18:00","wed":"9:00-18:00","thu":"9:00-18:00","fri":"9:00-18:00","sat":"10:00-15:00","sun":"closed"}'::jsonb,
  ARRAY[]::text[],
  true, true
),
(
  'mock-017',
  'Детски кабинет Усмивка',
  'Проверен',
  'Стара Загора',
  'ул. 22, Стара Загора',
  42.4528, 25.6635,
  'Детски кабинет Усмивка предлага професионални услуги в категория Специалисти. Опит, качество, индивидуален подход. Работим с деца от различни възрастови групи. Сертифицирани специалисти.',
  ARRAY['Терапия', 'Консултация', 'Диагностика', 'Групова терапия'],
  ARRAY['Специалисти'],
  ARRAY['6-12', 'Тийнейджъри', '3-5'],
  'https://placehold.co/200x200/2e994d/white?text=M017',
  131, false,
  '+359 88 289 0697',
  'biz017@example.bg',
  'https://example17.bg',
  'https://facebook.com/biz17', null,
  'Резервирай', 'https://example17.bg/book',
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-018',
  'Учебен център Знание',
  'Проверен',
  'Русе',
  'ул. 35, Русе',
  43.9144, 26.0317,
  'Учебен център Знание предлага професионални услуги в категория Учене и умения. Опит, качество, индивидуален подход. Работим с деца от различни възрастови групи. Сертифицирани специалисти.',
  ARRAY['Курсове', 'Уроци', 'Лятна школа', 'Олимпиади'],
  ARRAY['Учене и умения'],
  ARRAY['13-19'],
  'https://placehold.co/200x200/2e994d/white?text=M018',
  144, false,
  '+359 88 306 0738',
  'biz018@example.bg',
  'https://example18.bg',
  'https://facebook.com/biz18', 'https://instagram.com/biz18',
  'Резервирай', 'https://example18.bg/book',
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-019',
  'Adventure Zone',
  'Проверен',
  'Велико Търново',
  'ул. 48, Велико Търново',
  43.1647, 25.6202,
  'Adventure Zone предлага професионални услуги в категория Игри и забавления. Опит, качество, индивидуален подход. Работим с деца от различни възрастови групи. Сертифицирани специалисти.',
  ARRAY['Парти', 'Аниматори', 'Игри', 'Творчество'],
  ARRAY['Игри и забавления'],
  ARRAY['Тийнейджъри', '3-5'],
  'https://placehold.co/200x200/2e994d/white?text=M019',
  77, false,
  '+359 88 323 0779',
  'biz019@example.bg',
  'https://example19.bg',
  'https://facebook.com/biz19', null,
  'Резервирай', 'https://example19.bg/book',
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-020',
  'Музей за деца',
  'Проверен',
  'Онлайн',
  null,
  null, null,
  'Музей за деца предлага професионални услуги в категория Култура. Опит, качество, индивидуален подход. Работим с деца от различни възрастови групи. Сертифицирани специалисти.',
  ARRAY['Представления', 'Уъркшопи', 'Работилници', 'Лагери'],
  ARRAY['Култура'],
  ARRAY['0-3', '6-12', 'Тийнейджъри'],
  'https://placehold.co/200x200/2e994d/white?text=M020',
  90, false,
  null,
  'biz020@example.bg',
  'https://example20.bg',
  'https://facebook.com/biz20', 'https://instagram.com/biz20',
  'Резервирай', 'https://example20.bg/book',
  null, null,
  '{"mon":"9:00-18:00","tue":"9:00-18:00","wed":"9:00-18:00","thu":"9:00-18:00","fri":"9:00-18:00","sat":"10:00-15:00","sun":"closed"}'::jsonb,
  ARRAY[]::text[],
  true, true
),
(
  'mock-021',
  'Тенис академия',
  'Проверен',
  'София',
  'ул. 74, София',
  42.7487, 23.3989,
  'Тенис академия предлага професионални услуги в категория Спорт и движение. Опит, качество, индивидуален подход. Работим с деца от различни възрастови групи. Сертифицирани специалисти.',
  ARRAY['Тренировки', 'Турнири', 'Лагер', 'Лични уроци'],
  ARRAY['Спорт и движение'],
  ARRAY['3-5'],
  'https://placehold.co/200x200/2e994d/white?text=M021',
  103, true,
  '+359 88 357 0861',
  'biz021@example.bg',
  'https://example21.bg',
  'https://facebook.com/biz21', null,
  'Резервирай', 'https://example21.bg/book',
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-022',
  'Сладкарница Принц',
  'Проверен',
  'София',
  'ул. 87, София',
  42.7797, 23.3359,
  'Сладкарница Принц предлага професионални услуги в категория Тържества и събития. Опит, качество, индивидуален подход. Работим с деца от различни възрастови групи. Сертифицирани специалисти.',
  ARRAY['Аниматори', 'Декорация', 'Кетъринг', 'Фото'],
  ARRAY['Тържества и събития'],
  ARRAY['6-12', 'Тийнейджъри'],
  'https://placehold.co/200x200/2e994d/white?text=M022',
  116, false,
  '+359 88 374 0902',
  'biz022@example.bg',
  'https://example22.bg',
  'https://facebook.com/biz22', 'https://instagram.com/biz22',
  'Резервирай', 'https://example22.bg/book',
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-023',
  'Играчки Магия',
  'Проверен',
  'София',
  'ул. 100, София',
  42.7107, 23.3729,
  'Играчки Магия предлага професионални услуги в категория Стоки. Опит, качество, индивидуален подход. Работим с деца от различни възрастови групи. Сертифицирани специалисти.',
  ARRAY['Дрехи', 'Играчки', 'Аксесоари', 'Книги'],
  ARRAY['Стоки'],
  ARRAY['13-19', '0-3', '6-12'],
  'https://placehold.co/200x200/2e994d/white?text=M023',
  129, false,
  '+359 88 391 0943',
  'biz023@example.bg',
  'https://example23.bg',
  'https://facebook.com/biz23', null,
  'Резервирай', 'https://example23.bg/book',
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-024',
  'Au Pair Bulgaria',
  'Проверен',
  'София',
  'ул. 113, София',
  42.7417, 23.4099,
  'Au Pair Bulgaria предлага професионални услуги в категория Домашна грижа и помощ. Опит, качество, индивидуален подход. Работим с деца от различни възрастови групи. Сертифицирани специалисти.',
  ARRAY['Домашни услуги', 'Бавачка', 'Помощ', 'Грижа'],
  ARRAY['Домашна грижа и помощ'],
  ARRAY['Тийнейджъри'],
  'https://placehold.co/200x200/2e994d/white?text=M024',
  142, false,
  '+359 88 408 0984',
  'biz024@example.bg',
  'https://example24.bg',
  'https://facebook.com/biz24', 'https://instagram.com/biz24',
  'Резервирай', 'https://example24.bg/book',
  null, null,
  '{"mon":"9:00-18:00","tue":"9:00-18:00","wed":"9:00-18:00","thu":"9:00-18:00","fri":"9:00-18:00","sat":"10:00-15:00","sun":"closed"}'::jsonb,
  ARRAY[]::text[],
  true, true
),
(
  'mock-025',
  'Хранене за деца ProBaby',
  'Проверен',
  'София',
  'ул. 126, София',
  42.7727, 23.3469,
  'Хранене за деца ProBaby предлага професионални услуги в категория Специалисти. Опит, качество, индивидуален подход. Работим с деца от различни възрастови групи. Сертифицирани специалисти.',
  ARRAY['Терапия', 'Консултация', 'Диагностика', 'Групова терапия'],
  ARRAY['Специалисти'],
  ARRAY['0-3', '6-12'],
  'https://placehold.co/200x200/2e994d/white?text=M025',
  75, false,
  null,
  'biz025@example.bg',
  'https://example25.bg',
  'https://facebook.com/biz25', null,
  'Резервирай', 'https://example25.bg/book',
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-026',
  'EduStart Sofia',
  'Проверен',
  'София',
  'ул. 139, София',
  42.7037, 23.3839,
  'EduStart Sofia предлага професионални услуги в категория Учене и умения. Опит, качество, индивидуален подход. Работим с деца от различни възрастови групи. Сертифицирани специалисти.',
  ARRAY['Курсове', 'Уроци', 'Лятна школа', 'Олимпиади'],
  ARRAY['Учене и умения'],
  ARRAY['3-5', '13-19', '0-3'],
  'https://placehold.co/200x200/2e994d/white?text=M026',
  88, false,
  '+359 88 442 1066',
  'biz026@example.bg',
  'https://example26.bg',
  'https://facebook.com/biz26', 'https://instagram.com/biz26',
  'Резервирай', 'https://example26.bg/book',
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-027',
  'Funland Bulgaria',
  'Проверен',
  'София',
  'ул. 152, София',
  42.7347, 23.4209,
  'Funland Bulgaria предлага професионални услуги в категория Игри и забавления. Опит, качество, индивидуален подход. Работим с деца от различни възрастови групи. Сертифицирани специалисти.',
  ARRAY['Парти', 'Аниматори', 'Игри', 'Творчество'],
  ARRAY['Игри и забавления'],
  ARRAY['6-12'],
  'https://placehold.co/200x200/2e994d/white?text=M027',
  101, false,
  '+359 88 459 1107',
  'biz027@example.bg',
  'https://example27.bg',
  'https://facebook.com/biz27', null,
  'Резервирай', 'https://example27.bg/book',
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-028',
  'Арт студио Палитра',
  'Проверен',
  'София',
  'ул. 165, София',
  42.7657, 23.3579,
  'Арт студио Палитра предлага професионални услуги в категория Култура. Опит, качество, индивидуален подход. Работим с деца от различни възрастови групи. Сертифицирани специалисти.',
  ARRAY['Представления', 'Уъркшопи', 'Работилници', 'Лагери'],
  ARRAY['Култура'],
  ARRAY['13-19', '0-3'],
  'https://placehold.co/200x200/2e994d/white?text=M028',
  114, true,
  '+359 88 476 1148',
  'biz028@example.bg',
  'https://example28.bg',
  'https://facebook.com/biz28', 'https://instagram.com/biz28',
  'Резервирай', 'https://example28.bg/book',
  null, null,
  '{"mon":"9:00-18:00","tue":"9:00-18:00","wed":"9:00-18:00","thu":"9:00-18:00","fri":"9:00-18:00","sat":"10:00-15:00","sun":"closed"}'::jsonb,
  ARRAY[]::text[],
  true, true
),
(
  'mock-029',
  'Карате клуб Дракон',
  'Проверен',
  'Пловдив',
  'ул. 178, Пловдив',
  42.2344, 24.8183,
  'Карате клуб Дракон предлага професионални услуги в категория Спорт и движение. Опит, качество, индивидуален подход. Работим с деца от различни възрастови групи. Сертифицирани специалисти.',
  ARRAY['Тренировки', 'Турнири', 'Лагер', 'Лични уроци'],
  ARRAY['Спорт и движение'],
  ARRAY['Тийнейджъри', '3-5', '13-19'],
  'https://placehold.co/200x200/2e994d/white?text=M029',
  127, false,
  '+359 88 493 1189',
  'biz029@example.bg',
  'https://example29.bg',
  'https://facebook.com/biz29', null,
  'Резервирай', 'https://example29.bg/book',
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-030',
  'Фотограф Деца',
  'Проверен',
  'Пловдив',
  'ул. 191, Пловдив',
  42.1654, 24.7553,
  'Фотограф Деца предлага професионални услуги в категория Тържества и събития. Опит, качество, индивидуален подход. Работим с деца от различни възрастови групи. Сертифицирани специалисти.',
  ARRAY['Аниматори', 'Декорация', 'Кетъринг', 'Фото'],
  ARRAY['Тържества и събития'],
  ARRAY['0-3'],
  'https://placehold.co/200x200/2e994d/white?text=M030',
  140, false,
  null,
  'biz030@example.bg',
  'https://example30.bg',
  'https://facebook.com/biz30', 'https://instagram.com/biz30',
  'Резервирай', 'https://example30.bg/book',
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-031',
  'Книжарница Знание',
  'Проверен',
  'Пловдив',
  'ул. 4, Пловдив',
  42.1964, 24.7923,
  'Книжарница Знание предлага професионални услуги в категория Стоки. Опит, качество, индивидуален подход. Работим с деца от различни възрастови групи. Сертифицирани специалисти.',
  ARRAY['Дрехи', 'Играчки', 'Аксесоари', 'Книги'],
  ARRAY['Стоки'],
  ARRAY['3-5', '13-19'],
  'https://placehold.co/200x200/2e994d/white?text=M031',
  73, false,
  '+359 88 527 1271',
  'biz031@example.bg',
  'https://example31.bg',
  'https://facebook.com/biz31', null,
  'Резервирай', 'https://example31.bg/book',
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-032',
  'Домашен майстор Татко',
  'Проверен',
  'Варна',
  'ул. 17, Варна',
  43.3061, 27.9987,
  'Домашен майстор Татко предлага професионални услуги в категория Домашна грижа и помощ. Опит, качество, индивидуален подход. Работим с деца от различни възрастови групи. Сертифицирани специалисти.',
  ARRAY['Домашни услуги', 'Бавачка', 'Помощ', 'Грижа'],
  ARRAY['Домашна грижа и помощ'],
  ARRAY['6-12', 'Тийнейджъри', '3-5'],
  'https://placehold.co/200x200/2e994d/white?text=M032',
  86, false,
  '+359 88 544 1312',
  'biz032@example.bg',
  'https://example32.bg',
  'https://facebook.com/biz32', 'https://instagram.com/biz32',
  'Резервирай', 'https://example32.bg/book',
  null, null,
  '{"mon":"9:00-18:00","tue":"9:00-18:00","wed":"9:00-18:00","thu":"9:00-18:00","fri":"9:00-18:00","sat":"10:00-15:00","sun":"closed"}'::jsonb,
  ARRAY[]::text[],
  true, true
),
(
  'mock-033',
  'Терапевтичен център Хармония',
  'Проверен',
  'Варна',
  'ул. 30, Варна',
  43.2371, 27.9357,
  'Терапевтичен център Хармония предлага професионални услуги в категория Специалисти. Опит, качество, индивидуален подход. Работим с деца от различни възрастови групи. Сертифицирани специалисти.',
  ARRAY['Терапия', 'Консултация', 'Диагностика', 'Групова терапия'],
  ARRAY['Специалисти'],
  ARRAY['13-19'],
  'https://placehold.co/200x200/2e994d/white?text=M033',
  99, false,
  '+359 88 561 1353',
  'biz033@example.bg',
  'https://example33.bg',
  'https://facebook.com/biz33', null,
  'Резервирай', 'https://example33.bg/book',
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-034',
  'STEM Lab',
  'Проверен',
  'Варна',
  'ул. 43, Варна',
  43.2681, 27.9727,
  'STEM Lab предлага професионални услуги в категория Учене и умения. Опит, качество, индивидуален подход. Работим с деца от различни възрастови групи. Сертифицирани специалисти.',
  ARRAY['Курсове', 'Уроци', 'Лятна школа', 'Олимпиади'],
  ARRAY['Учене и умения'],
  ARRAY['Тийнейджъри', '3-5'],
  'https://placehold.co/200x200/2e994d/white?text=M034',
  112, false,
  '+359 88 578 1394',
  'biz034@example.bg',
  'https://example34.bg',
  'https://facebook.com/biz34', 'https://instagram.com/biz34',
  'Резервирай', 'https://example34.bg/book',
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-035',
  'Виртуална реалност Кидс',
  'Проверен',
  'Бургас',
  'ул. 56, Бургас',
  42.5898, 27.5576,
  'Виртуална реалност Кидс предлага професионални услуги в категория Игри и забавления. Опит, качество, индивидуален подход. Работим с деца от различни възрастови групи. Сертифицирани специалисти.',
  ARRAY['Парти', 'Аниматори', 'Игри', 'Творчество'],
  ARRAY['Игри и забавления'],
  ARRAY['0-3', '6-12', 'Тийнейджъри'],
  'https://placehold.co/200x200/2e994d/white?text=M035',
  125, true,
  null,
  'biz035@example.bg',
  'https://example35.bg',
  'https://facebook.com/biz35', null,
  'Резервирай', 'https://example35.bg/book',
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-036',
  'Танцов клуб Ритъм',
  'Стандартен',
  'Бургас',
  'ул. 69, Бургас',
  42.5208, 27.4946,
  null,
  ARRAY['Представления', 'Уъркшопи'],
  ARRAY['Култура'],
  ARRAY['3-5'],
  'https://placehold.co/200x200/777/white?text=M036',
  71, false,
  '+359 88 612 1476',
  'biz036@example.bg',
  'https://example36.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-037',
  'Гимнастика за деца',
  'Стандартен',
  'Стара Загора',
  'ул. 82, Стара Загора',
  42.4728, 25.7035,
  null,
  ARRAY['Тренировки', 'Турнири'],
  ARRAY['Спорт и движение'],
  ARRAY['6-12', 'Тийнейджъри'],
  'https://placehold.co/200x200/777/white?text=M037',
  42, false,
  '+359 88 629 1517',
  'biz037@example.bg',
  'https://example37.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-038',
  'Декор Праз',
  'Стандартен',
  'Русе',
  'ул. 95, Русе',
  43.9344, 25.9717,
  null,
  ARRAY['Аниматори', 'Декорация'],
  ARRAY['Тържества и събития'],
  ARRAY['13-19', '0-3', '6-12'],
  'https://placehold.co/200x200/777/white?text=M038',
  53, false,
  '+359 88 646 1558',
  'biz038@example.bg',
  'https://example38.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-039',
  'Био храни ЕКО',
  'Стандартен',
  'Велико Търново',
  'ул. 108, Велико Търново',
  43.0847, 25.6602,
  null,
  ARRAY['Дрехи', 'Играчки'],
  ARRAY['Стоки'],
  ARRAY['Тийнейджъри'],
  'https://placehold.co/200x200/777/white?text=M039',
  64, false,
  '+359 88 663 1599',
  'biz039@example.bg',
  'https://example39.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-040',
  'Услуги за дома',
  'Стандартен',
  'Онлайн',
  null,
  null, null,
  null,
  ARRAY['Домашни услуги', 'Бавачка'],
  ARRAY['Домашна грижа и помощ'],
  ARRAY['0-3', '6-12'],
  'https://placehold.co/200x200/777/white?text=M040',
  35, false,
  null,
  'biz040@example.bg',
  'https://example40.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-041',
  'Семеен психолог Петров',
  'Стандартен',
  'София',
  'ул. 134, София',
  42.7687, 23.3389,
  null,
  ARRAY['Терапия', 'Консултация'],
  ARRAY['Специалисти'],
  ARRAY['3-5', '13-19', '0-3'],
  'https://placehold.co/200x200/777/white?text=M041',
  46, false,
  '+359 88 697 1681',
  'biz041@example.bg',
  'https://example41.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-042',
  'Smart Kids School',
  'Стандартен',
  'София',
  'ул. 147, София',
  42.6997, 23.3759,
  null,
  ARRAY['Курсове', 'Уроци'],
  ARRAY['Учене и умения'],
  ARRAY['6-12'],
  'https://placehold.co/200x200/777/white?text=M042',
  57, true,
  '+359 88 714 1722',
  'biz042@example.bg',
  'https://example42.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-043',
  'Trampoline Park',
  'Стандартен',
  'София',
  'ул. 160, София',
  42.7307, 23.4129,
  null,
  ARRAY['Парти', 'Аниматори'],
  ARRAY['Игри и забавления'],
  ARRAY['13-19', '0-3'],
  'https://placehold.co/200x200/777/white?text=M043',
  68, false,
  '+359 88 731 1763',
  'biz043@example.bg',
  'https://example43.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-044',
  'Школа по балет',
  'Стандартен',
  'София',
  'ул. 173, София',
  42.7617, 23.3499,
  null,
  ARRAY['Представления', 'Уъркшопи'],
  ARRAY['Култура'],
  ARRAY['Тийнейджъри', '3-5', '13-19'],
  'https://placehold.co/200x200/777/white?text=M044',
  39, false,
  '+359 88 748 1804',
  'biz044@example.bg',
  'https://example44.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-045',
  'Баскетбол JR',
  'Стандартен',
  'София',
  'ул. 186, София',
  42.7927, 23.3869,
  null,
  ARRAY['Тренировки', 'Турнири'],
  ARRAY['Спорт и движение'],
  ARRAY['0-3'],
  'https://placehold.co/200x200/777/white?text=M045',
  50, false,
  null,
  'biz045@example.bg',
  'https://example45.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-046',
  'Под наем Костюми',
  'Стандартен',
  'София',
  'ул. 199, София',
  42.7237, 23.3239,
  null,
  ARRAY['Аниматори', 'Декорация'],
  ARRAY['Тържества и събития'],
  ARRAY['3-5', '13-19'],
  'https://placehold.co/200x200/777/white?text=M046',
  61, false,
  '+359 88 782 1886',
  'biz046@example.bg',
  'https://example46.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-047',
  'Безопасност за дома',
  'Стандартен',
  'София',
  'ул. 12, София',
  42.7547, 23.3609,
  null,
  ARRAY['Дрехи', 'Играчки'],
  ARRAY['Стоки'],
  ARRAY['6-12', 'Тийнейджъри', '3-5'],
  'https://placehold.co/200x200/777/white?text=M047',
  72, false,
  '+359 88 799 1927',
  'biz047@example.bg',
  'https://example47.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-048',
  'Помощ в къщи',
  'Стандартен',
  'София',
  'ул. 25, София',
  42.7857, 23.3979,
  null,
  ARRAY['Домашни услуги', 'Бавачка'],
  ARRAY['Домашна грижа и помощ'],
  ARRAY['13-19'],
  'https://placehold.co/200x200/777/white?text=M048',
  43, false,
  '+359 88 816 1968',
  'biz048@example.bg',
  'https://example48.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-049',
  'Сензорен център Звезда',
  'Стандартен',
  'Пловдив',
  'ул. 38, Пловдив',
  42.1544, 24.7583,
  null,
  ARRAY['Терапия', 'Консултация'],
  ARRAY['Специалисти'],
  ARRAY['Тийнейджъри', '3-5'],
  'https://placehold.co/200x200/777/white?text=M049',
  54, true,
  '+359 88 833 2009',
  'biz049@example.bg',
  'https://example49.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-050',
  'Език и култура',
  'Стандартен',
  'Пловдив',
  'ул. 51, Пловдив',
  42.1854, 24.7953,
  null,
  ARRAY['Курсове', 'Уроци'],
  ARRAY['Учене и умения'],
  ARRAY['0-3', '6-12', 'Тийнейджъри'],
  'https://placehold.co/200x200/777/white?text=M050',
  65, false,
  null,
  'biz050@example.bg',
  'https://example50.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-051',
  'Bowling Center Junior',
  'Стандартен',
  'Пловдив',
  'ул. 64, Пловдив',
  42.2164, 24.8323,
  null,
  ARRAY['Парти', 'Аниматори'],
  ARRAY['Игри и забавления'],
  ARRAY['3-5'],
  'https://placehold.co/200x200/777/white?text=M051',
  36, false,
  '+359 88 867 2091',
  'biz051@example.bg',
  'https://example51.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-052',
  'Музикална школа',
  'Стандартен',
  'Варна',
  'ул. 77, Варна',
  43.2261, 27.9387,
  null,
  ARRAY['Представления', 'Уъркшопи'],
  ARRAY['Култура'],
  ARRAY['6-12', 'Тийнейджъри'],
  'https://placehold.co/200x200/777/white?text=M052',
  47, false,
  '+359 88 884 2132',
  'biz052@example.bg',
  'https://example52.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-053',
  'Боен изкуства Нинджа',
  'Стандартен',
  'Варна',
  'ул. 90, Варна',
  43.2571, 27.9757,
  null,
  ARRAY['Тренировки', 'Турнири'],
  ARRAY['Спорт и движение'],
  ARRAY['13-19', '0-3', '6-12'],
  'https://placehold.co/200x200/777/white?text=M053',
  58, false,
  '+359 88 901 2173',
  'biz053@example.bg',
  'https://example53.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-054',
  'Балони и Парти',
  'Стандартен',
  'Варна',
  'ул. 103, Варна',
  43.2881, 28.0127,
  null,
  ARRAY['Аниматори', 'Декорация'],
  ARRAY['Тържества и събития'],
  ARRAY['Тийнейджъри'],
  'https://placehold.co/200x200/777/white?text=M054',
  69, false,
  '+359 88 918 2214',
  'biz054@example.bg',
  'https://example54.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-055',
  'Tech Toys Bulgaria',
  'Стандартен',
  'Бургас',
  'ул. 116, Бургас',
  42.5098, 27.4976,
  null,
  ARRAY['Дрехи', 'Играчки'],
  ARRAY['Стоки'],
  ARRAY['0-3', '6-12'],
  'https://placehold.co/200x200/777/white?text=M055',
  40, false,
  null,
  'biz055@example.bg',
  'https://example55.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-056',
  'Чистачка с деца',
  'Стандартен',
  'Бургас',
  'ул. 129, Бургас',
  42.5408, 27.5346,
  null,
  ARRAY['Домашни услуги', 'Бавачка'],
  ARRAY['Домашна грижа и помощ'],
  ARRAY['3-5', '13-19', '0-3'],
  'https://placehold.co/200x200/777/white?text=M056',
  51, true,
  '+359 88 952 2296',
  'biz056@example.bg',
  'https://example56.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-057',
  'Дентална клиника Smile',
  'Стандартен',
  'Стара Загора',
  'ул. 142, Стара Загора',
  42.4928, 25.6435,
  null,
  ARRAY['Терапия', 'Консултация'],
  ARRAY['Специалисти'],
  ARRAY['6-12'],
  'https://placehold.co/200x200/777/white?text=M057',
  62, false,
  '+359 88 969 2337',
  'biz057@example.bg',
  'https://example57.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-058',
  'Code Wizards',
  'Стандартен',
  'Русе',
  'ул. 155, Русе',
  43.9544, 26.0117,
  null,
  ARRAY['Курсове', 'Уроци'],
  ARRAY['Учене и умения'],
  ARRAY['13-19', '0-3'],
  'https://placehold.co/200x200/777/white?text=M058',
  73, false,
  '+359 88 986 2378',
  'biz058@example.bg',
  'https://example58.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-059',
  'Лазерен лабиринт',
  'Стандартен',
  'Велико Търново',
  'ул. 168, Велико Търново',
  43.1047, 25.7002,
  null,
  ARRAY['Парти', 'Аниматори'],
  ARRAY['Игри и забавления'],
  ARRAY['Тийнейджъри', '3-5', '13-19'],
  'https://placehold.co/200x200/777/white?text=M059',
  44, false,
  '+359 88 003 2419',
  'biz059@example.bg',
  'https://example59.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-060',
  'Творческа академия',
  'Стандартен',
  'Онлайн',
  null,
  null, null,
  null,
  ARRAY['Представления', 'Уъркшопи'],
  ARRAY['Култура'],
  ARRAY['0-3'],
  'https://placehold.co/200x200/777/white?text=M060',
  55, false,
  null,
  'biz060@example.bg',
  'https://example60.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-061',
  'Аеробика и танц',
  'Стандартен',
  'София',
  'ул. 194, София',
  42.7887, 23.3789,
  null,
  ARRAY['Тренировки', 'Турнири'],
  ARRAY['Спорт и движение'],
  ARRAY['3-5', '13-19'],
  'https://placehold.co/200x200/777/white?text=M061',
  66, false,
  '+359 88 037 2501',
  'biz061@example.bg',
  'https://example61.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-062',
  'Магически шоу',
  'Стандартен',
  'София',
  'ул. 7, София',
  42.7197, 23.4159,
  null,
  ARRAY['Аниматори', 'Декорация'],
  ARRAY['Тържества и събития'],
  ARRAY['6-12', 'Тийнейджъри', '3-5'],
  'https://placehold.co/200x200/777/white?text=M062',
  37, false,
  '+359 88 054 2542',
  'biz062@example.bg',
  'https://example62.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-063',
  'Конзоли и игри',
  'Стандартен',
  'София',
  'ул. 20, София',
  42.7507, 23.3529,
  null,
  ARRAY['Дрехи', 'Играчки'],
  ARRAY['Стоки'],
  ARRAY['13-19'],
  'https://placehold.co/200x200/777/white?text=M063',
  48, true,
  '+359 88 071 2583',
  'biz063@example.bg',
  'https://example63.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-064',
  'Сити Бавачки',
  'Стандартен',
  'София',
  'ул. 33, София',
  42.7817, 23.3899,
  null,
  ARRAY['Домашни услуги', 'Бавачка'],
  ARRAY['Домашна грижа и помощ'],
  ARRAY['Тийнейджъри', '3-5'],
  'https://placehold.co/200x200/777/white?text=M064',
  59, false,
  '+359 88 088 2624',
  'biz064@example.bg',
  'https://example64.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-065',
  'Speech Therapy Plus',
  'Стандартен',
  'София',
  'ул. 46, София',
  42.7127, 23.3269,
  null,
  ARRAY['Терапия', 'Консултация'],
  ARRAY['Специалисти'],
  ARRAY['0-3', '6-12', 'Тийнейджъри'],
  'https://placehold.co/200x200/777/white?text=M065',
  70, false,
  null,
  'biz065@example.bg',
  'https://example65.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-066',
  'Music Academy Sound',
  'Стандартен',
  'София',
  'ул. 59, София',
  42.7437, 23.3639,
  null,
  ARRAY['Курсове', 'Уроци'],
  ARRAY['Учене и умения'],
  ARRAY['3-5'],
  'https://placehold.co/200x200/777/white?text=M066',
  41, false,
  '+359 88 122 2706',
  'biz066@example.bg',
  'https://example66.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-067',
  'Аркаден център',
  'Стандартен',
  'София',
  'ул. 72, София',
  42.7747, 23.4009,
  null,
  ARRAY['Парти', 'Аниматори'],
  ARRAY['Игри и забавления'],
  ARRAY['6-12', 'Тийнейджъри'],
  'https://placehold.co/200x200/777/white?text=M067',
  52, false,
  '+359 88 139 2747',
  'biz067@example.bg',
  'https://example67.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-068',
  'Кино за деца',
  'Стандартен',
  'София',
  'ул. 85, София',
  42.7057, 23.3379,
  null,
  ARRAY['Представления', 'Уъркшопи'],
  ARRAY['Култура'],
  ARRAY['13-19', '0-3', '6-12'],
  'https://placehold.co/200x200/777/white?text=M068',
  63, false,
  '+359 88 156 2788',
  'biz068@example.bg',
  'https://example68.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-069',
  'Конна база',
  'Стандартен',
  'Пловдив',
  'ул. 98, Пловдив',
  42.1744, 24.7983,
  null,
  ARRAY['Тренировки', 'Турнири'],
  ARRAY['Спорт и движение'],
  ARRAY['Тийнейджъри'],
  'https://placehold.co/200x200/777/white?text=M069',
  74, false,
  '+359 88 173 2829',
  'biz069@example.bg',
  'https://example69.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-070',
  'Кетъринг Малчугани',
  'Стандартен',
  'Пловдив',
  'ул. 111, Пловдив',
  42.2054, 24.8353,
  null,
  ARRAY['Аниматори', 'Декорация'],
  ARRAY['Тържества и събития'],
  ARRAY['0-3', '6-12'],
  'https://placehold.co/200x200/777/white?text=M070',
  45, true,
  null,
  'biz070@example.bg',
  'https://example70.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-071',
  'Памперси онлайн',
  'Стандартен',
  'Пловдив',
  'ул. 124, Пловдив',
  42.1364, 24.7723,
  null,
  ARRAY['Дрехи', 'Играчки'],
  ARRAY['Стоки'],
  ARRAY['3-5', '13-19', '0-3'],
  'https://placehold.co/200x200/777/white?text=M071',
  56, false,
  '+359 88 207 2911',
  'biz071@example.bg',
  'https://example71.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-072',
  'Family Helper',
  'Стандартен',
  'Варна',
  'ул. 137, Варна',
  43.2461, 27.9787,
  null,
  ARRAY['Домашни услуги', 'Бавачка'],
  ARRAY['Домашна грижа и помощ'],
  ARRAY['6-12'],
  'https://placehold.co/200x200/777/white?text=M072',
  67, false,
  '+359 88 224 2952',
  'biz072@example.bg',
  'https://example72.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-073',
  'Кинезитерапия за деца',
  'Стандартен',
  'Варна',
  'ул. 150, Варна',
  43.2771, 27.9157,
  null,
  ARRAY['Терапия', 'Консултация'],
  ARRAY['Специалисти'],
  ARRAY['13-19', '0-3'],
  'https://placehold.co/200x200/777/white?text=M073',
  38, false,
  '+359 88 241 2993',
  'biz073@example.bg',
  'https://example73.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-074',
  'Творческа работилница',
  'Стандартен',
  'Варна',
  'ул. 163, Варна',
  43.3081, 27.9527,
  null,
  ARRAY['Курсове', 'Уроци'],
  ARRAY['Учене и умения'],
  ARRAY['Тийнейджъри', '3-5', '13-19'],
  'https://placehold.co/200x200/777/white?text=M074',
  49, false,
  '+359 88 258 3034',
  'biz074@example.bg',
  'https://example74.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-075',
  'Игрален свят',
  'Стандартен',
  'Бургас',
  'ул. 176, Бургас',
  42.5298, 27.5376,
  null,
  ARRAY['Парти', 'Аниматори'],
  ARRAY['Игри и забавления'],
  ARRAY['0-3'],
  'https://placehold.co/200x200/777/white?text=M075',
  60, false,
  null,
  'biz075@example.bg',
  'https://example75.bg',
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-076',
  'Художествена студия',
  'Безплатен',
  'Бургас',
  'ул. 189, Бургас',
  42.5608, 27.4746,
  null,
  ARRAY['Представления'],
  ARRAY['Култура'],
  ARRAY['3-5', '13-19'],
  'https://placehold.co/200x200/bbb/white?text=M076',
  42, false,
  '+359 88 292 3116',
  'biz076@example.bg',
  null,
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-077',
  'Кид Фитнес',
  'Безплатен',
  'Стара Загора',
  'ул. 2, Стара Загора',
  42.5128, 25.6835,
  null,
  ARRAY['Тренировки'],
  ARRAY['Спорт и движение'],
  ARRAY['6-12', 'Тийнейджъри', '3-5'],
  'https://placehold.co/200x200/bbb/white?text=M077',
  49, true,
  '+359 88 309 3157',
  'biz077@example.bg',
  null,
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-078',
  'Event Studio Kids',
  'Безплатен',
  'Русе',
  'ул. 15, Русе',
  43.8744, 26.0517,
  null,
  ARRAY['Аниматори'],
  ARRAY['Тържества и събития'],
  ARRAY['13-19'],
  'https://placehold.co/200x200/bbb/white?text=M078',
  41, false,
  '+359 88 326 3198',
  'biz078@example.bg',
  null,
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-079',
  'Spa за бебета',
  'Безплатен',
  'Велико Търново',
  'ул. 28, Велико Търново',
  43.1247, 25.6402,
  null,
  ARRAY['Дрехи'],
  ARRAY['Стоки'],
  ARRAY['Тийнейджъри', '3-5'],
  'https://placehold.co/200x200/bbb/white?text=M079',
  48, false,
  '+359 88 343 3239',
  'biz079@example.bg',
  null,
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-080',
  'Home Care Kids',
  'Безплатен',
  'Онлайн',
  null,
  null, null,
  null,
  ARRAY['Домашни услуги'],
  ARRAY['Домашна грижа и помощ'],
  ARRAY['0-3', '6-12', 'Тийнейджъри'],
  'https://placehold.co/200x200/bbb/white?text=M080',
  40, false,
  null,
  'biz080@example.bg',
  null,
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-081',
  'Д-р Иванова Психология #1',
  'Безплатен',
  'София',
  'ул. 54, София',
  42.7087, 23.4189,
  null,
  ARRAY['Терапия'],
  ARRAY['Специалисти'],
  ARRAY['3-5'],
  'https://placehold.co/200x200/bbb/white?text=M081',
  47, false,
  '+359 88 377 3321',
  'biz081@example.bg',
  null,
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-082',
  'Little Engineers #1',
  'Безплатен',
  'София',
  'ул. 67, София',
  42.7397, 23.3559,
  null,
  ARRAY['Курсове'],
  ARRAY['Учене и умения'],
  ARRAY['6-12', 'Тийнейджъри'],
  'https://placehold.co/200x200/bbb/white?text=M082',
  39, false,
  '+359 88 394 3362',
  'biz082@example.bg',
  null,
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-083',
  'Детски център Слънчо #1',
  'Безплатен',
  'София',
  'ул. 80, София',
  42.7707, 23.3929,
  null,
  ARRAY['Парти'],
  ARRAY['Игри и забавления'],
  ARRAY['13-19', '0-3', '6-12'],
  'https://placehold.co/200x200/bbb/white?text=M083',
  46, false,
  '+359 88 411 3403',
  'biz083@example.bg',
  null,
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-084',
  'Театър Пинокио #1',
  'Безплатен',
  'София',
  'ул. 93, София',
  42.7017, 23.3299,
  null,
  ARRAY['Представления'],
  ARRAY['Култура'],
  ARRAY['Тийнейджъри'],
  'https://placehold.co/200x200/bbb/white?text=M084',
  38, true,
  '+359 88 428 3444',
  'biz084@example.bg',
  null,
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-085',
  'Футболна школа Виктория #1',
  'Безплатен',
  'София',
  'ул. 106, София',
  42.7327, 23.3669,
  null,
  ARRAY['Тренировки'],
  ARRAY['Спорт и движение'],
  ARRAY['0-3', '6-12'],
  'https://placehold.co/200x200/bbb/white?text=M085',
  45, false,
  null,
  'biz085@example.bg',
  null,
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-086',
  'Парти зала Феерия #1',
  'Безплатен',
  'София',
  'ул. 119, София',
  42.7637, 23.4039,
  null,
  ARRAY['Аниматори'],
  ARRAY['Тържества и събития'],
  ARRAY['3-5', '13-19', '0-3'],
  'https://placehold.co/200x200/bbb/white?text=M086',
  37, false,
  '+359 88 462 3526',
  'biz086@example.bg',
  null,
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-087',
  'Бебешки магазин Бамби #1',
  'Безплатен',
  'София',
  'ул. 132, София',
  42.7947, 23.3409,
  null,
  ARRAY['Дрехи'],
  ARRAY['Стоки'],
  ARRAY['6-12'],
  'https://placehold.co/200x200/bbb/white?text=M087',
  44, false,
  '+359 88 479 3567',
  'biz087@example.bg',
  null,
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-088',
  'Детегледач СЪН #1',
  'Безплатен',
  'София',
  'ул. 145, София',
  42.7257, 23.3779,
  null,
  ARRAY['Домашни услуги'],
  ARRAY['Домашна грижа и помощ'],
  ARRAY['13-19', '0-3'],
  'https://placehold.co/200x200/bbb/white?text=M088',
  36, false,
  '+359 88 496 3608',
  'biz088@example.bg',
  null,
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-089',
  'Логопед Студио Реч #1',
  'Безплатен',
  'Пловдив',
  'ул. 158, Пловдив',
  42.1944, 24.8383,
  null,
  ARRAY['Терапия'],
  ARRAY['Специалисти'],
  ARRAY['Тийнейджъри', '3-5', '13-19'],
  'https://placehold.co/200x200/bbb/white?text=M089',
  43, false,
  '+359 88 513 3649',
  'biz089@example.bg',
  null,
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-090',
  'Robo Academy #1',
  'Безплатен',
  'Пловдив',
  'ул. 171, Пловдив',
  42.2254, 24.7753,
  null,
  ARRAY['Курсове'],
  ARRAY['Учене и умения'],
  ARRAY['0-3'],
  'https://placehold.co/200x200/bbb/white?text=M090',
  35, false,
  null,
  'biz090@example.bg',
  null,
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-091',
  'Игротека Дъга #1',
  'Безплатен',
  'Пловдив',
  'ул. 184, Пловдив',
  42.1564, 24.8123,
  null,
  ARRAY['Парти'],
  ARRAY['Игри и забавления'],
  ARRAY['3-5', '13-19'],
  'https://placehold.co/200x200/bbb/white?text=M091',
  42, true,
  '+359 88 547 3731',
  'biz091@example.bg',
  null,
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-092',
  'Куклен театър Капчица #1',
  'Безплатен',
  'Варна',
  'ул. 197, Варна',
  43.2661, 27.9187,
  null,
  ARRAY['Представления'],
  ARRAY['Култура'],
  ARRAY['6-12', 'Тийнейджъри', '3-5'],
  'https://placehold.co/200x200/bbb/white?text=M092',
  49, false,
  '+359 88 564 3772',
  'biz092@example.bg',
  null,
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-093',
  'Плувен клуб Делфин #1',
  'Безплатен',
  'Варна',
  'ул. 10, Варна',
  43.2971, 27.9557,
  null,
  ARRAY['Тренировки'],
  ARRAY['Спорт и движение'],
  ARRAY['13-19'],
  'https://placehold.co/200x200/bbb/white?text=M093',
  41, false,
  '+359 88 581 3813',
  'biz093@example.bg',
  null,
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-094',
  'Аниматори Усмивка #1',
  'Безплатен',
  'Варна',
  'ул. 23, Варна',
  43.2281, 27.9927,
  null,
  ARRAY['Аниматори'],
  ARRAY['Тържества и събития'],
  ARRAY['Тийнейджъри', '3-5'],
  'https://placehold.co/200x200/bbb/white?text=M094',
  48, false,
  '+359 88 598 3854',
  'biz094@example.bg',
  null,
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-095',
  'Дрехи KidStyle #1',
  'Безплатен',
  'Бургас',
  'ул. 36, Бургас',
  42.5498, 27.4776,
  null,
  ARRAY['Дрехи'],
  ARRAY['Стоки'],
  ARRAY['0-3', '6-12', 'Тийнейджъри'],
  'https://placehold.co/200x200/bbb/white?text=M095',
  40, false,
  null,
  'biz095@example.bg',
  null,
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-096',
  'Бавачка PRO #1',
  'Безплатен',
  'Бургас',
  'ул. 49, Бургас',
  42.5808, 27.5146,
  null,
  ARRAY['Домашни услуги'],
  ARRAY['Домашна грижа и помощ'],
  ARRAY['3-5'],
  'https://placehold.co/200x200/bbb/white?text=M096',
  47, false,
  '+359 88 632 3936',
  'biz096@example.bg',
  null,
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-097',
  'Детски кабинет Усмивка #1',
  'Безплатен',
  'Стара Загора',
  'ул. 62, Стара Загора',
  42.4328, 25.7235,
  null,
  ARRAY['Терапия'],
  ARRAY['Специалисти'],
  ARRAY['6-12', 'Тийнейджъри'],
  'https://placehold.co/200x200/bbb/white?text=M097',
  39, false,
  '+359 88 649 3977',
  'biz097@example.bg',
  null,
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-098',
  'Учебен център Знание #1',
  'Безплатен',
  'Русе',
  'ул. 75, Русе',
  43.8944, 25.9917,
  null,
  ARRAY['Курсове'],
  ARRAY['Учене и умения'],
  ARRAY['13-19', '0-3', '6-12'],
  'https://placehold.co/200x200/bbb/white?text=M098',
  46, true,
  '+359 88 666 4018',
  'biz098@example.bg',
  null,
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-099',
  'Adventure Zone #1',
  'Безплатен',
  'Велико Търново',
  'ул. 88, Велико Търново',
  43.1447, 25.6802,
  null,
  ARRAY['Парти'],
  ARRAY['Игри и забавления'],
  ARRAY['Тийнейджъри'],
  'https://placehold.co/200x200/bbb/white?text=M099',
  38, false,
  '+359 88 683 4059',
  'biz099@example.bg',
  null,
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
),
(
  'mock-100',
  'Музей за деца #1',
  'Безплатен',
  'Онлайн',
  null,
  null, null,
  null,
  ARRAY['Представления'],
  ARRAY['Култура'],
  ARRAY['0-3', '6-12'],
  'https://placehold.co/200x200/bbb/white?text=M100',
  45, false,
  null,
  'biz100@example.bg',
  null,
  null, null,
  null, null,
  null, null,
  null,
  ARRAY[]::text[],
  true, true
)
ON CONFLICT (legacy_id) DO UPDATE SET
  name = EXCLUDED.name,
  tier = EXCLUDED.tier,
  city = EXCLUDED.city,
  address = EXCLUDED.address,
  lat = EXCLUDED.lat,
  lng = EXCLUDED.lng,
  description = EXCLUDED.description,
  services = EXCLUDED.services,
  categories = EXCLUDED.categories,
  age_groups = EXCLUDED.age_groups,
  logo = EXCLUDED.logo,
  audit_score = EXCLUDED.audit_score,
  sop = EXCLUDED.sop,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  website = EXCLUDED.website,
  facebook = EXCLUDED.facebook,
  instagram = EXCLUDED.instagram,
  cta_label_1 = EXCLUDED.cta_label_1,
  cta_url_1 = EXCLUDED.cta_url_1,
  cta_label_2 = EXCLUDED.cta_label_2,
  cta_url_2 = EXCLUDED.cta_url_2,
  working_hours = EXCLUDED.working_hours,
  gallery_urls = EXCLUDED.gallery_urls,
  published = EXCLUDED.published,
  is_sample = EXCLUDED.is_sample;

-- Verify the insert
SELECT
  count(*) AS total_rows,
  count(*) FILTER (WHERE tier = 'Доверен')   AS doveren,
  count(*) FILTER (WHERE tier = 'Проверен')  AS proveren,
  count(*) FILTER (WHERE tier = 'Стандартен') AS standarten,
  count(*) FILTER (WHERE tier = 'Безплатен') AS bezplaten,
  count(*) FILTER (WHERE sop = true) AS sop_count,
  count(*) FILTER (WHERE description IS NOT NULL) AS with_description,
  count(*) FILTER (WHERE working_hours IS NOT NULL) AS with_hours
FROM public.businesses
WHERE legacy_id LIKE 'mock-%';
